name: Go

on:
  push:
    branches:
    - master
    - 'go/**'
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'
  pull_request:
    paths:
    - 'go/**'
    - '.github/workflows/go.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: go
      format-pkgs: golang-1.17 libsdl2-dev
      build-pkgs: golang-1.17 libsdl2-dev
      cache-paths: |
        ~/.cache/go-build
        ~/go/pkg/mod
      cache-file: '**/go.sum'
      nix-flake: true
