name: PHP

on:
  push:
    branches:
    - master
    - develop
    - 'php/**'
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  pull_request:
    paths:
    - 'php/**'
    - '.github/workflows/php.yml'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: php
      format-pkgs: php-cli
      build-pkgs: php-cli
      nix-flake: true
