name: Rust

on:
  push:
    branches:
    - master
    - develop
    - 'rs/**'
    paths:
    - 'rs/**'
    - '.github/workflows/rs.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  pull_request:
    paths:
    - 'rs/**'
    - '.github/workflows/rs.yml'
    - '.github/workflows/common.yml'
    - 'flake.*'
  workflow_dispatch:

jobs:
  common:
    name: Common
    uses: ./.github/workflows/common.yml
    with:
      workdir: rs
      format-pkgs: cargo
      build-pkgs: gcc libsdl2-dev cargo
      cache-paths: |
        ~/.cargo
        rs/target
      cache-file: '**/Cargo.lock'
      nix-flake: true
